from BaseClasses import Item, ItemClassification

class PTItem(Item):
    game: str = "Pizza Tower"

pt_items = {
    "Toppin": (101, ItemClassification.progression_skip_balancing),
    "Boss Key": (102, ItemClassification.progression),
    "Lap 2 Portals": (149, ItemClassification.useful),

    "Mach 4": (103, ItemClassification.progression),
    "Uppercut": (104, ItemClassification.progression),
    "Superjump": (105, ItemClassification.progression),
    "Grab": (106, ItemClassification.progression),
    #ID 107 has been reassigned to "Bomb"
    "Taunt": (108, ItemClassification.progression),
    "Supertaunt": (109, ItemClassification.progression),
    "Bodyslam": (110, ItemClassification.progression),
    "Breakdance": (111, ItemClassification.filler),

    "Wallclimb": (112, ItemClassification.progression),
    #"Dive": (113, ItemClassification.useful),
    "Double Jump": (114, ItemClassification.progression),
    "Rat Kick": (115, ItemClassification.progression),
    #"Wall Jump": (116, ItemClassification.progression),
    "Spin Attack": (117, ItemClassification.useful),

    "Wallbounce": (118, ItemClassification.progression),
    "Tornado": (119, ItemClassification.progression),
    "Crusher": (120, ItemClassification.progression),
    "Bomb": (107, ItemClassification.progression),

    "Clown Trap": (121, ItemClassification.trap),
    "Timer Trap": (122, ItemClassification.trap),
    "Ghost Trap": (123, ItemClassification.trap),
    "Fake Santa Trap": (124, ItemClassification.trap),
    "Oktoberfest!": (125, ItemClassification.trap),
    "Granny Trap": (147, ItemClassification.trap),

    "Permanent 10 Points": (126, ItemClassification.filler),
    "Permanent 50 Points": (127, ItemClassification.filler),
    "Permanent 100 Points": (128, ItemClassification.filler),
    "Primo Burg": (129, ItemClassification.filler),
    "Cross Buff": (130, ItemClassification.filler),
    "Pizza Shield": (131, ItemClassification.filler),

    #transfo items; may get used someday but not right now
    "Ball": (132, ItemClassification.progression),
    "Knight": (133, ItemClassification.progression),
    "Firemouth": (134, ItemClassification.progression),
    "Ghost": (135, ItemClassification.progression),
    "Mort": (136, ItemClassification.progression),
    "Weenie": (137, ItemClassification.progression),
    "Barrel": (138, ItemClassification.progression),
    "Anti-Grav Bubble": (139, ItemClassification.progression),
    "Rocket": (140, ItemClassification.progression),
    "Pizzabox": (141, ItemClassification.progression),
    "Sticky Cheese": (142, ItemClassification.progression),
    "Satan's Choice": (143, ItemClassification.progression),
    "Shotgun": (144, ItemClassification.progression),
    "Revolver": (145, ItemClassification.progression),

    "Nothing": (146, ItemClassification.filler),

    "Jumpscare": (148, ItemClassification.trap), #replaces oktoberfest if options.jumpscare == true

    #clothes
    "Clothes: Classic Cook": (300, ItemClassification.filler), #unused
    "Clothes: Unfunny Cook": (301, ItemClassification.filler),
    "Clothes: Money Green": (302, ItemClassification.filler),
    "Clothes: SAGE Blue": (303, ItemClassification.filler),
    "Clothes: Blood Red": (304, ItemClassification.filler),
    "Clothes: TV Purple": (305, ItemClassification.filler),
    "Clothes: Dark Cook": (306, ItemClassification.filler),
    "Clothes: Shitty Cook": (307, ItemClassification.filler),
    "Clothes: Golden God": (308, ItemClassification.filler),
    "Clothes: Garish Cook": (309, ItemClassification.filler),
    "Clothes: Mooney Orange": (310, ItemClassification.filler),
    "Clothes: Funny Polka": (311, ItemClassification.filler),
    "Clothes: Itchy Sweater": (312, ItemClassification.filler),
    "Clothes: Pizza Man": (313, ItemClassification.filler),
    "Clothes: Bowling Stripes": (314, ItemClassification.filler),
    "Clothes: Goldemanne": (315, ItemClassification.filler),
    "Clothes: Bad Bones": (316, ItemClassification.filler),
    "Clothes: PP Shirt": (317, ItemClassification.filler),
    "Clothes: War Camo": (318, ItemClassification.filler),
    "Clothes: John Suit": (319, ItemClassification.filler),
    "Clothes: Noise": (320, ItemClassification.filler), #unused
    "Clothes: Boise": (321, ItemClassification.filler),
    "Clothes: Roise": (322, ItemClassification.filler),
    "Clothes: Poise": (323, ItemClassification.filler),
    "Clothes: Reverse": (324, ItemClassification.filler),
    "Clothes: Critic": (325, ItemClassification.filler),
    "Clothes: Outlaw": (326, ItemClassification.filler),
    "Clothes: Anti-Doise": (327, ItemClassification.filler),
    "Clothes: Flesh Eater": (328, ItemClassification.filler),
    "Clothes: Super": (329, ItemClassification.filler),
    "Clothes: Fast Porcupine": (330, ItemClassification.filler),
    "Clothes: Feminine Side": (331, ItemClassification.filler),
    "Clothes: The Real Doise": (332, ItemClassification.filler),
    "Clothes: Forest Goblin": (333, ItemClassification.filler),
    "Clothes: Racer": (334, ItemClassification.filler),
    "Clothes: Comedian": (335, ItemClassification.filler),
    "Clothes: Banana": (336, ItemClassification.filler),
    "Clothes: Noise TV": (337, ItemClassification.filler),
    "Clothes: Madman": (338, ItemClassification.filler),
    "Clothes: Bubbly": (339, ItemClassification.filler),
    "Clothes: Well Done": (340, ItemClassification.filler),
    "Clothes: Granny Kisses": (341, ItemClassification.filler),
    "Clothes: Tower Guy": (342, ItemClassification.filler),
    "Clothes: Candy Wrapper": (343, ItemClassification.filler),
    "Clothes: Bloodstained": (344, ItemClassification.filler),
    "Clothes: Autumn": (345, ItemClassification.filler),
    "Clothes: Pumpkin": (346, ItemClassification.filler),
    "Clothes: Fur": (347, ItemClassification.filler),
    "Clothes: Eyes": (348, ItemClassification.filler),
}